#!/bin/bash

# In the future, we may support this script being invoked from elsewhere
# (someone's going to do it...)
cd $OE_HOME

git submodule init
echo '*****************************************************************'
echo '***** Downloading submodules.  This may take some time: ******'
echo '*****************************************************************'
if ( ! git submodule update )
	then
	echo "ERROR: failed to update submodules"
	echo "This seems to happen quite often -- invoke this script again."
	echo '(Check your net connection is up too!)'
	exit
fi

echo "Checkout complete."
echo "To continue your building quest, do the following in your shell:"
echo "% . sr/profile.sh"
echo "% bitbake sr-image"

